import {
  BatteryCharging,
  Briefcase,
  Building2,
  Cable,
  ClipboardList,
  Clock,
  Cloud,
  Compass,
  Database,
  Gift,
  Handshake,
  Heart,
  KeyRound,
  Layers,
  LifeBuoy,
  Mail,
  Monitor,
  MonitorSmartphone,
  Network,
  PackageCheck,
  PackageSearch,
  PenTool,
  Rocket,
  Server,
  ServerCrash,
  Settings,
  ShieldCheck,
  ThumbsUp,
  Truck,
  Users2,
  Wallet,
  Wifi,
  Wrench,
  Zap,
} from 'lucide-react';

// Shared name -> lucide-react component registry. Every lib/content.js data
// array that carries an `icon` string field resolves it through this single
// map, so a name that's missing here fails the same way in every consumer
// instead of silently rendering `undefined` in whichever local map forgot it.
export const ICONS = {
  BatteryCharging,
  Briefcase,
  Building2,
  Cable,
  ClipboardList,
  Clock,
  Cloud,
  Compass,
  Database,
  Gift,
  Handshake,
  Heart,
  KeyRound,
  Layers,
  LifeBuoy,
  Mail,
  Monitor,
  MonitorSmartphone,
  Network,
  PackageCheck,
  PackageSearch,
  PenTool,
  Rocket,
  Server,
  ServerCrash,
  Settings,
  ShieldCheck,
  ThumbsUp,
  Truck,
  Users2,
  Wallet,
  Wifi,
  Wrench,
  Zap,
};
