import {
  Building2,
  Cable,
  ClipboardList,
  Clock,
  Compass,
  Heart,
  Layers,
  LifeBuoy,
  MonitorSmartphone,
  Network,
  PackageCheck,
  PackageSearch,
  PenTool,
  Rocket,
  Server,
  ServerCrash,
  ShieldCheck,
  ThumbsUp,
  Truck,
  Users2,
  Wifi,
  Wrench,
  Zap,
} from 'lucide-react';

// Shared name -> lucide-react component registry. Every lib/content.js data
// array that carries an `icon` string field resolves it through this single
// map, so a name that's missing here fails the same way in every consumer
// instead of silently rendering `undefined` in whichever local map forgot it.
export const ICONS = {
  Building2,
  Cable,
  ClipboardList,
  Clock,
  Compass,
  Heart,
  Layers,
  LifeBuoy,
  MonitorSmartphone,
  Network,
  PackageCheck,
  PackageSearch,
  PenTool,
  Rocket,
  Server,
  ServerCrash,
  ShieldCheck,
  ThumbsUp,
  Truck,
  Users2,
  Wifi,
  Wrench,
  Zap,
};
